#!/bin/bash

PROJECT_PATH=$(cat "$VIRTUAL_ENV/.project")
TAGS_PATH=$VIRTUAL_ENV/.vim/
PYTHON_PATH=$VIRTUAL_ENV/lib/python2.7/

if [ ! -d $TAGS_PATH ]; then
    echo "Creating ctags path..."
    mkdir -p $TAGS_PATH
fi

echo "Updating ctags..."
/usr/local/bin/ctags -R -f $TAGS_PATH/python.ctags $PYTHON_PATH

if [ -d $PROJECT_PATH ]; then
    /usr/local/bin/ctags -R -f $TAGS_PATH/project.ctags $PROJECT_PATH
fi
